http:
  client:
    # 重试次数
    retryCount: 3
    # 长连接保持时间（单位：s）
    keepAliveTime: 30
    manager:
      # 最大连接数
      maxTotal: 100
      # 并发数
      defaultMaxPerRoute: 20
      # 连接上服务器(握手成功)的时间，超出该时间抛出 connect timeout（单位：ms）
      connectTimeout: 1000
      # 可用空闲连接过期时间，重用空闲连接时会先检查是否空闲时间超过这个时间，如果超过，释放 socket 重新建立（单位：ms）
      validateAfterInactivity: 30000
      # 连接存活时间（单位：s）
      timeToLive: 60
    request:
      # 从连接池中获取到连接的最长时间（单位：ms），超过该时间未拿到可用连接，会抛出 org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
      connectionRequestTimeout: 500
      # 服务器返回数据(response)的时间，超过该时间抛出 read timeout（单位：ms）
      socketTimeout: 10000
    proxy:
      # 代理的 host 地址
      proxyHost: "127.0.0.1"
      # 代理的端口号
      proxyPort: 1080